import { defineConfig, presetWind4, presetIcons, presetAttributify, presetTagify } from "unocss";

export default defineConfig({
  presets: [
    presetWind4(),
    presetAttributify(),
    presetTagify({
      extraProperties: (matched) => 
        matched.startsWith('i-') ? { display: 'inline-block', 'vertical-align': 'middle' } : {}
    }),
    presetIcons({
      scale: 1.2,
      warn: true,
      extraProperties: {
        'display': 'inline-block',
        'vertical-align': 'middle',
        'width': '1.2em',
        'height': '1.2em',
      },
    }),
  ],
  safelist: [
    'i-ph-arrow-left-bold',
    'i-ph-shopping-bag-light',
    'i-ph-trash-bold',
    'i-ph-minus-bold',
    'i-ph-plus-bold',
    'i-ph-caret-double-right-bold',
    'i-ph-clock-bold',
    'i-ph-shield-check-bold',
    'i-ph-house-line',
    'i-ph-house-line-duotone',
    'i-ph-list-bullets',
    'i-ph-list-bullets-duotone',
    'i-ph-notepad',
    'i-ph-notepad-duotone',
    'i-ph-user',
    'i-ph-user-duotone',
    'flex',
    'flex-col',
    'items-center',
    'justify-center',
    'py-20',
    'bg-neutral-50',
    'rounded-3xl',
    'border-2',
    'border-dashed',
    'border-neutral-200',
    'animate-fade-in',
    'text-6xl',
    'text-neutral-300',
    'mb-4',
    'text-neutral-500',
    'text-lg',
    'font-bold',
    'text-neutral-400',
    'text-sm',
    'mb-6',
    'px-8',
    'py-3',
    'bg-neutral-900',
    'text-white',
    'rounded-xl',
    'hover:bg-neutral-800',
    'transition-all',
    'cart-item',
    'bg-white',
    'border',
    'border-neutral-100',
    'p-5',
    'hover:shadow-xl',
    'hover:border-yellow-200',
    'md:flex-row',
    'gap-5',
    'w-full',
    'md:w-24',
    'h-24',
    'object-cover',
    'rounded-2xl',
    'flex-1',
    'justify-between',
    'items-start',
    'text-neutral-900',
    'leading-tight',
    'text-xs',
    'mt-1',
    'line-clamp-1',
    'p-2',
    'hover:text-red-500',
    'hover:bg-red-50',
    'text-xl',
    'flex-wrap',
    'gap-4',
    'mt-4',
    'gap-3',
    'p-1.5',
    'w-8',
    'h-8',
    'border-neutral-200',
    'min-w-10',
    'text-center',
    'font-black',
    'text-right',
    'text-[9px]',
    'uppercase',
    'tracking-widest',
    'leading-none',
    'mb-1'
  ]
});
